name: Linux CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.6

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/MobilePorting/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: |
          haxelib run lime rebuild linux -32 -release -nocolor -nocffi
          haxelib run lime rebuild linux -64 -release -nocolor -nocffi
      - name: Upload Artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Linux-NDLL
          path: |
            ndll/Linux/
            !**/.gitignore
            lime.png
          if-no-files-found: error
      - name: Upload Artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: Linux64-NDLL
          path: |
            ndll/Linux64/
            !**/.gitignore
            lime.png
          if-no-files-found: error